package questionbank;


public class ComputerNetwork {
  public  static String nw[]=
{"How many digits of the DNIC (Data Network Identification Code) identify the country?",
"A station in a network forwards incoming packets by placing them on its shortest output queue. What routing algorithm is being used?",
"The probability that a single bit will be in error on a typical public telephone line using 4800 bps modem is 10 to the power -3. If no error detection mechanism is used, the residual error rate for a communication line using 9-bit frames is approximately equal to",
"Frames from one LAN can be transmitted to another LAN via the device",
"Which of the following condition is used to transmit two packets over a medium at the same time?",
"You have a class A network address 10.0.0.0 with 40 subnets, but are required to add 60 new subnets very soon. You would like to still allow for the largest possible number of host IDs per subnet. Which subnet mask should you assign?",
"What are the most commonly used transmission speeds in BPS used in data communication?",
"What is the default subnet mask for a class C network?",
"Which of the following is used for modulation and demodulation?",
"Which of the following is not a disadvantage of wireless LAN?",
"The Internet Control Message Protocol (ICMP)",
"Your company has a LAN in its downtown office and has now set up a LAN in the manufacturing plant in the suburbs. To enable everyone to share data and resources between the two LANs, what type of device(s) are needed to connect them? ",
"The term \'duplex\' refers to the ability of the data receiving stations to echo back a confirming message to the sender. In full duplex data transmission, both the sender and the receiver",
"How many hosts are attached to each of the local area networks at your site?",
"Which of the following technique is used for fragment?",
"Contention is",
"Avalanche photodiode receivers can detect hits of transmitted data by receiving",
"Satellite-Switched Time-Division Multiple Access (SS/TDMA) is",
"When you ping the loopback address, a packet is sent where?",
"Which of the following TCP/IP protocol is used for transferring electronic mail messages from one machine to another?",
"Which of the following device is used to connect two systems, especially if the systems use different protocols?",
"The synchronous modems are more costly than the asynchronous modems because",
"A distributed network configuration in which all data/information pass through a central computer is",
"Which of the following TCP/IP protocol allows an application program on one machine to send a datagram to an application program on another machine?",
"A remote batch-processing operation in which data is solely input to a central computer would require a:",
"Mode of communication in which transmission takes place in both direction at same time is called-",
"Topology with highest reliability is-",
"Start and stop bits are used for-",
" Pick the system that can be used in priority and non-priority mode-",
"The ____ translates internet domain and host names to IP address.",
"Which transmission media has the highest transmission speed in a network?",
" Which one of the following task is not done by data link layer?",
"CRC stands for",
"Which one of the following is a data link protocol?",
" The network layer concerns with",
"Which one of the following is a transport layer protocol used in internet?",
"The packet of information at the application layer is called",
" This is a time-sensitive service",
"In the network HTTP resources are located by",
"In file transfer protocol, data transfer can be done in"
};
    
  public  static String nwchoice[][]={{"first three","first four","first five","first six"},
{"hot potato routing","flooding","static routing","delta routing"},
{"0.003","0.009","0.991","0.999"},
{"Router","Bridge","Repeater","Modem"},
{"Contention","Collision","Synchronous","Asynchronous"},
{"255.240.0.0","255.248.0.0","255.252.0.0","255.254.0.0"},
{"300","1200","2400","9600"},
{"127.0.0.1","255.0.0.0","255.255.0.0","255.255.255.0"},
{"modem","protocols","gateway","multiplexer"},
{"Slower data transmission","higher error rate","interference of transmissions from different computers","All of the above"},
{"allows gateways to send error a control messages to other gateways or hosts",
"provides communication between the Internet Protocol Software on one machine and the Internet Protocol Software on another",
"reports error conditions to the original source, the source must relate errors to individual application programs and take action to correct the problem",
"All of the above"},
{"Modem","Cable","Hub","Router"},
{"cannot talk at once","can receive and send data simultaneously","can send or receive data one at a time","can do one way data transmission only"},
{"128","254","256","64"},
{"a technique used in best-effort delivery systems to avoid endlessly looping packets","a technique used by protocols in which a lower level protocol accepts a message from a higher level protocol and places it in the data portion of the low level frame","one of the pieces that results when an IP gateway divides an IP datagram into smaller pieces for transmission across a network that cannot handle the original datagram size","All of the above"},
{"One or more conductors that serve as a common connection for a related group of devices","a continuous frequency capable of being modulated or impressed with a second signal","the condition when two or more stations attempt to use the same channel at the same time","a collection of interconnected functional units that provides a data communications service among stations attached to the network"},
{"100 photons","200 photons","300 photons","400 photons"},
{"the method of determining which device has access to the transmission medium at any time.","a medium access control technique for multiple access transmission media","a form of TDMA in which circuit switching is used to dynamically change the channel assignments","All of the above"},
{"On the network","Down through the layers of the IP architecture and then up the layers again","Across the wire","through the loopback dongle"},
{"FTP","SNMP","SMTP","RPC"},
{"hub","bridge","gateway","repeater"},
{"they produce large volume of data","they contain clock recovery circuits","they transmit the data with stop and start bits.","they operate with a larger bandwidth"},
{"bus network","star network","ring network","Point-to-point network"},
{"UDP","VMTP","	X.25","SMTP"},
{"telegraph line","simplex lines","mixedband channel","	All the above"},
{"Simplex","Half duplex"," Full duplex"," None"},
{"Bus"," Star","Ring"," Mesh"},
{"Error detection","Error correction","Synchronization","All"},
{"TDM","Register insertion","FDM","Token passing"},
{"domain name system","routing information protocol","network time protocol"," internet relay chat"},
{"coaxial cable"," twisted pair cable","optical fiber","electrical cable"},
{"framing","error control","flow control","channel coding"},
{" cyclic redundancy check","code repeat check","code redundancy check"," cyclic repeat check"},
{"ethernet","point to point protocol"," HDLC","all of the mentioned"},
{"bits","frames","packets","none of the mentioned"},
{"TCP","UDP","both (a) and (b)"," none of the mentioned"},
{"Packet","Message"," Segment","Frame"},
{"File transfer","File download","E-mail","Internet telephony"},
{"uniform resource identifier","unique resource locator","unique resource identifier","none of the mentioned"},
{"stream mode"," block mode","compressed mode"," all of the mentioned"}};
   
  public  static String nwans[]={"A","A","B","B","B","D","D","D","A","D","D","D","B","B","C","C","B","C","B","C","C",
"B","B","A","B","C","D","C","D","A","C","D","A","D","C","C","B","D","A","D"};
    
    
    
    
}
