package questionbank;
public class SE {
 
	public static String se[]={"SDLC refers to-","Process model is also known as-",
"Which is not a phase of RAD model-",
"How many levels are present in CMM-",
"CMM level 2 refers to-",
"SSPI stands for-",
"The functional requirements describes-",
"The requirement analysis act as a bridge between-",
"Which is the element of analysis model-",
"SRS also called as-",
"what are the important issues which an SRS document must address-",
"S/W design is an _ process-",
 "which is not a designing concept-",
"which is not a UML diagram-",
"which come under architectural styles-",
"which is not the fundalmental principal of user interface design-",
"SA/SD carrying out two distince activities-",
"clear box testing also refers to-",
"which is not a COCOMO model-",
"Who writes the Software Requirement Specifications Document(SRS)?",
"What is the final outcome of the requirements analysis and specifications phase?",
" Which of the following is not a desirable characteristic of SRS document?",
"Spiral Model was developed by?",
" Which is not a software life cycle model",
"Project risk factor is considered in ?",
"Waterfall model is not suitable for ?",
"Which of the following is a tool in design phase ?",
"Black box testing sometimes called ?",
".... is a black box testing method ?",
"Data structure suitable for the application is discussed in ?",
"In functional decomposition, the data flow diagram ?",
"A graphic representation of an information system is called ?",
"The model remains operative until the software is retired  ?",
"RAD is not appropriate when ?",
"CMM is",
"RUP and PSP stands for",
"A test plan may contain all but",
"Which of the following is not a graphical language for software design:",
"Use case description contents includes ?",
"Product developement is a central business activity because ?"};

	public static String sechoice[][]={{" System Development life cycle"," system deployment life cycle"," s/w development life cycle"," s/w deployment life cycle"},
{"Waterfall model","Iterative  model"," S/W engineering process","S/W engineering paradigm"},
{"Business modelling"," Data  modelling","Process  modelling","Deployment modelling"},
{"3","5"," 4"," 6"},
{"Initial","Repeatable"," Defined"," Managed"},
{"Statistical S/W Product Initialization","S/W System  Product Initialization","Statistical S/W Process Improvement","System S/W Product Improvement"},
{"External requirements","External interfaces","Organizational requirments"," Product requirements"},
{"system engineering & s/w design","s/w enginering & s/w developer","system design & system engineering","All of the above"},
{"data dictionary","data flow diagram"," control specification"," all of the above"},
{"white-box specification","black-box specification","documentary model","none of the above"},
{"performance","functionality","neither (1) nor (2)"," both (1) and (2)"},
{"important","iterative"," revolutionary","all of the above"},
{"data structure","informative riding"," cost estimation","control hierarchy"},
{"sequence dig","deployment dig"," component dig"," none of the above"},
{"data contered","layered","call & return","all of the above"},
{" familiarity"," consistency","diversity","reliability"},
{"structured analysis and structured design"," system analysis and system design"," s/w analysis and s/w design","s/w analysis and s/w development"},
{"functional testing","black box testing"," white box testing","orthogonal array testing"},
{"basic","intermediate","advanced","All are cocomo model type"},
{"System Developer","System Tester"," System Analyst"," None of these above"},
{"Drawing the data flow diagram","The SRS Document","Coding the project"," The User Manual"},
{"Concise","Ambiguous","Traceable","Verifiable"},
{"Bev Littlewood","Berry Bohem"," Roger Pressman","Victor Bisili"},
{"Spiral Model","Waterfall Model","Prototyping Model","Capability maturity Model"},
{"Spiral Model","Waterfall Model","Prototyping Model","Iterative enhancement Model"},
{"Small Projects","Complex Projects","Accommodating change"," None of Above"},
{"Abstraction","Refinement","Information Hiding","All of Above"},
{"Data Flow testing","Loop Testing","Behavioral Testing","Graph Based Testing"},
{"Boundary value analysis","Basic path testing","Code path analysis","None of above"},
{"data design","architectural design","procedural design","interface design"},
{"is ignored","is partitioned according to the closeness of the datagram and storage items","is partitioned according to the logical closeness of the actigram","Both A and C"},
{"Flow chart","Pictogram","Data flow diagram","Histogram"},
{"Waterfall","Incremental","Spiral","None of these"},
{"Fast finding already done","Technical risks are high","Testing is not needed","None of above"},
{"Company maturity model"," Capability maturity model","Configuration maturity model","Company management model"},
{"Realtime unified process and Project software process"," Realtime unified process and Personal software process","Rational Unified Process and Project software process","Rational Unified Process and Personal software process"},
{"traceability screenshots","test data"," test set","traceability requirements"},
{"UML","DML","EEML","SysML"},
{"Use case name and number","Actors","Stakeholder and needs","All of the mentioned"},
{"It is expensive and complicated","It determines organization’s future","It is risky","All of the mentioned"}};



	public static String seans[]={"C","D","D","D","B","C","B","A","D","B","D","B","C","D","D","D",
"A","C","D","C","B","B","B","D","A","C","D","C","A","A","C","C","C","B","B","D","A","B","D","D"};
    
    
    
}
